In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('datasets/iris.csv')
X = dataset.iloc[0:100,[0,1,2,3]].values
Y = dataset.iloc[0:100,4].values

Y = np.where(Y == 'Iris-setosa', 0, 1)

weights = np.array([0.0,0.0,0.0,0.0])
bias = 0.0

In [4]:
print("X:\n",X)
print("Y:\n",Y)

X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

In [10]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def forward_propogation(X,W,b):
    weighted_sum = np.dot(X,W)+b
    prediction = sigmoid(weighted_sum)
    return prediction

def gradient(X,Y,Y_predicted):
    '''Gradient of Weights and Bias'''
    Error = Y_predicted - Y
    dW = np.dot(X.T,Error)
    db = np.sum(Error)
    return dW,db

def update_parametes(W,b,dW,db,learning_rate):
    W = W - learning_rate * dW
    b = b - learning_rate * db
    return W,b

def train(X,Y,W,b):
    epochs = 1000
    learning_rate = 0.1

    for i in range(epochs):
        Y_predicted = forward_propogation(X,W,b)
        dW,db = gradient(X,Y,Y_predicted)
        W,b = update_parametes(W,b,dW,db,learning_rate)
        

    return W,b



In [11]:
#Model Training
W,b = train(X,Y,weights,bias)

In [15]:
print("Weights: ",W)
print("Bias: ",b)

Weights:  [-10.05918155 -28.97067093  40.56208393  17.38650129]
Bias:  -5.212156909710928


In [14]:
#predicting value
print("Target Value")
print(Y)
A2 = forward_propogation(X,W,b)

print("Predicted Value")
Y_predicted = (A2 > 0.5) * 1
print(Y_predicted)

Target Value
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Predicted Value
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [13]:
#Compare predicted and actual labels

comparision = Y_predicted == Y
equal_arrays = comparision.all()
print("Prediction Accuracy: ",equal_arrays)

Prediction Accuracy:  True
